# API
api.base-url=https://restful-booker.herokuapp.com
api.graphql-url=https://api-eu-central-1.hygraph.com/v2/clxxxxxxxxxxxxxxxxxx/master
api.connect-timeout=10000
api.read-timeout=30000
api.username=${BOOKING_USERNAME}
api.password=${BOOKING_PASSWORD}

# GraphQL
graphql.base-path=classpath:graphql/

# UI
ui.base-url=https://demoqa.com
ui.browser=chromium
ui.headless=true
ui.slow-mo=0
ui.timeout=30000
